version: '3.9'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=romario.sarmiento
      - POSTGRES_PASSWORD=123admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=romariosc15@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80
